// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: mmtp.proto

package mmtp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_UNSPECIFIED_MESSAGE MsgType = 0
	MsgType_PROTOCOL_MESSAGE    MsgType = 1
	MsgType_RESPONSE_MESSAGE    MsgType = 2
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "UNSPECIFIED_MESSAGE",
		1: "PROTOCOL_MESSAGE",
		2: "RESPONSE_MESSAGE",
	}
	MsgType_value = map[string]int32{
		"UNSPECIFIED_MESSAGE": 0,
		"PROTOCOL_MESSAGE":    1,
		"RESPONSE_MESSAGE":    2,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_mmtp_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_mmtp_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_mmtp_proto_rawDescGZIP(), []int{0}
}

type ProtocolMessageType int32

const (
	ProtocolMessageType_UNSPECIFIED         ProtocolMessageType = 0
	ProtocolMessageType_SUBSCRIBE_MESSAGE   ProtocolMessageType = 1
	ProtocolMessageType_UNSUBSCRIBE_MESSAGE ProtocolMessageType = 2
	ProtocolMessageType_SEND_MESSAGE        ProtocolMessageType = 3
	ProtocolMessageType_RECEIVE_MESSAGE     ProtocolMessageType = 4
	ProtocolMessageType_FETCH_MESSAGE       ProtocolMessageType = 5
	ProtocolMessageType_DISCONNECT_MESSAGE  ProtocolMessageType = 6
	ProtocolMessageType_CONNECT_MESSAGE     ProtocolMessageType = 7
	ProtocolMessageType_NOTIFY_MESSAGE      ProtocolMessageType = 8
)

// Enum value maps for ProtocolMessageType.
var (
	ProtocolMessageType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "SUBSCRIBE_MESSAGE",
		2: "UNSUBSCRIBE_MESSAGE",
		3: "SEND_MESSAGE",
		4: "RECEIVE_MESSAGE",
		5: "FETCH_MESSAGE",
		6: "DISCONNECT_MESSAGE",
		7: "CONNECT_MESSAGE",
		8: "NOTIFY_MESSAGE",
	}
	ProtocolMessageType_value = map[string]int32{
		"UNSPECIFIED":         0,
		"SUBSCRIBE_MESSAGE":   1,
		"UNSUBSCRIBE_MESSAGE": 2,
		"SEND_MESSAGE":        3,
		"RECEIVE_MESSAGE":     4,
		"FETCH_MESSAGE":       5,
		"DISCONNECT_MESSAGE":  6,
		"CONNECT_MESSAGE":     7,
		"NOTIFY_MESSAGE":      8,
	}
)

func (x ProtocolMessageType) Enum() *ProtocolMessageType {
	p := new(ProtocolMessageType)
	*p = x
	return p
}

func (x ProtocolMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtocolMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_mmtp_proto_enumTypes[1].Descriptor()
}

func (ProtocolMessageType) Type() protoreflect.EnumType {
	return &file_mmtp_proto_enumTypes[1]
}

func (x ProtocolMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtocolMessageType.Descriptor instead.
func (ProtocolMessageType) EnumDescriptor() ([]byte, []int) {
	return file_mmtp_proto_rawDescGZIP(), []int{1}
}

type ResponseEnum int32

const (
	ResponseEnum_UNSPECIFIED_RESPONSE ResponseEnum = 0
	ResponseEnum_GOOD                 ResponseEnum = 1
	ResponseEnum_ERROR                ResponseEnum = 2
)

// Enum value maps for ResponseEnum.
var (
	ResponseEnum_name = map[int32]string{
		0: "UNSPECIFIED_RESPONSE",
		1: "GOOD",
		2: "ERROR",
	}
	ResponseEnum_value = map[string]int32{
		"UNSPECIFIED_RESPONSE": 0,
		"GOOD":                 1,
		"ERROR":                2,
	}
)

func (x ResponseEnum) Enum() *ResponseEnum {
	p := new(ResponseEnum)
	*p = x
	return p
}

func (x ResponseEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_mmtp_proto_enumTypes[2].Descriptor()
}

func (ResponseEnum) Type() protoreflect.EnumType {
	return &file_mmtp_proto_enumTypes[2]
}

func (x ResponseEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseEnum.Descriptor instead.
func (ResponseEnum) EnumDescriptor() ([]byte, []int) {
	return file_mmtp_proto_rawDescGZIP(), []int{2}
}

type ApplicationMessage struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Header        *ApplicationMessageHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body          []byte                    `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Signature     []byte                    `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationMessage) Reset() {
	*x = ApplicationMessage{}
	mi := &file_mmtp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationMessage) ProtoMessage() {}

func (x *ApplicationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mmtp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationMessage.ProtoReflect.Descriptor instead.
func (*ApplicationMessage) Descriptor() ([]byte, []int) {
	return file_mmtp_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationMessage) GetHeader() *ApplicationMessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ApplicationMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ApplicationMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ApplicationMessageHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to SubjectOrRecipient:
	//
	//	*ApplicationMessageHeader_Subject
	//	*ApplicationMessageHeader_Recipients
	SubjectOrRecipient isApplicationMessageHeader_SubjectOrRecipient `protobuf_oneof:"SubjectOrRecipient"`
	Expires            int64                                         `protobuf:"varint,3,opt,name=expires,proto3" json:"expires,omitempty"`
	Sender             string                                        `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	QosProfile         *string                                       `protobuf:"bytes,5,opt,name=qosProfile,proto3,oneof" json:"qosProfile,omitempty"`
	BodySizeNumBytes   uint32                                        `protobuf:"varint,6,opt,name=bodySizeNumBytes,proto3" json:"bodySizeNumBytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ApplicationMessageHeader) Reset() {
	*x = ApplicationMessageHeader{}
	mi := &file_mmtp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationMessageHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationMessageHeader) ProtoMessage() {}

func (x *ApplicationMessageHeader) ProtoReflect() protoreflect.Message {
	mi := &file_mmtp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationMessageHeader.ProtoReflect.Descriptor instead.
func (*ApplicationMessageHeader) Descriptor() ([]byte, []int) {
	return file_mmtp_proto_rawDescGZIP(), []int{1}
}

func (x *ApplicationMessageHeader) GetSubjectOrRecipient() isApplicationMessageHeader_SubjectOrRecipient {
	if x != nil {
		return x.SubjectOrRecipient
	}
	return nil
}

func (x *ApplicationMessageHeader) GetSubject() string {
	if x != nil {
		if x, ok := x.SubjectOrRecipient.(*ApplicationMessageHeader_Subject); ok {
			return x.Subject
		}
	}
	return ""
}

func (x *ApplicationMessageHeader) GetRecipients() *Recipients {
	if x != nil {
		if x, ok := x.SubjectOrRecipient.(*ApplicationMessageHeader_Recipients); ok {
			return x.Recipients
		}
	}
	return nil
}

func (x *ApplicationMessageHeader) GetExpires() int64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

func (x *ApplicationMessageHeader) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ApplicationMessageHeader) GetQosProfile() string {
	if x != nil && x.QosProfile != nil {
		return *x.QosProfile
	}
	return ""
}

func (x *ApplicationMessageHeader) GetBodySizeNumBytes() uint32 {
	if x != nil {
		return x.BodySizeNumBytes
	}
	return 0
}

type isApplicationMessageHeader_SubjectOrRecipient interface {
	isApplicationMessageHeader_SubjectOrRecipient()
}

type ApplicationMessageHeader_Subject struct {
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3,oneof"`
}

type ApplicationMessageHeader_Recipients struct {
	Recipients *Recipients `protobuf:"bytes,2,opt,name=recipients,proto3,oneof"`
}

func (*ApplicationMessageHeader_Subject) isApplicationMessageHeader_SubjectOrRecipient() {}

func (*ApplicationMessageHeader_Recipients) isApplicationMessageHeader_SubjectOrRecipient() {}

type Recipients struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipients    []string               `protobuf:"bytes,1,rep,name=recipients,proto3" json:"recipients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recipients) Reset() {
	*x = Recipients{}
	mi := &file_mmtp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recipients) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipients) ProtoMessage() {}

func (x *Recipients) ProtoReflect() protoreflect.Message {
	mi := &file_mmtp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipients.ProtoReflect.Descriptor instead.
func (*Recipients) Descriptor() ([]byte, []int) {
	return file_mmtp_proto_rawDescGZIP(), []int{2}
}

func (x *Recipients) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

type MmtpMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	MsgType MsgType                `protobuf:"varint,1,opt,name=msgType,proto3,enum=MsgType" json:"msgType,omitempty"`
	Uuid    string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*MmtpMessage_ProtocolMessage
	//	*MmtpMessage_ResponseMessage
	Body          isMmtpMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MmtpMessage) Reset() {
	*x = MmtpMessage{}
	mi := &file_mmtp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MmtpMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MmtpMessage) ProtoMessage() {}

func (x *MmtpMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mmtp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MmtpMessage.ProtoReflect.Descriptor instead.
func (*MmtpMessage) Descriptor() ([]byte, []int) {
	return file_mmtp_proto_rawDescGZIP(), []int{3}
}

func (x *MmtpMessage) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_UNSPECIFIED_MESSAGE
}

func (x *MmtpMessage) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MmtpMessage) GetBody() isMmtpMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *MmtpMessage) GetProtocolMessage() *ProtocolMessage {
	if x != nil {
		if x, ok := x.Body.(*MmtpMessage_ProtocolMessage); ok {
			return x.ProtocolMessage
		}
	}
	return nil
}

func (x *MmtpMessage) GetResponseMessage() *ResponseMessage {
	if x != nil {
		if x, ok := x.Body.(*MmtpMessage_ResponseMessage); ok {
			return x.ResponseMessage
		}
	}
	return nil
}

type isMmtpMessage_Body interface {
	isMmtpMessage_Body()
}

type MmtpMessage_ProtocolMessage struct {
	ProtocolMessage *ProtocolMessage `protobuf:"bytes,3,opt,name=protocolMessage,proto3,oneof"`
}

type MmtpMessage_ResponseMessage struct {
	ResponseMessage *ResponseMessage `protobuf:"bytes,4,opt,name=responseMessage,proto3,oneof"`
}

func (*MmtpMessage_ProtocolMessage) isMmtpMessage_Body() {}

func (*MmtpMessage_ResponseMessage) isMmtpMessage_Body() {}

type ProtocolMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolMsgType ProtocolMessageType    `protobuf:"varint,1,opt,name=protocolMsgType,proto3,enum=ProtocolMessageType" json:"protocolMsgType,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*ProtocolMessage_SubscribeMessage
	//	*ProtocolMessage_UnsubscribeMessage
	//	*ProtocolMessage_SendMessage
	//	*ProtocolMessage_ReceiveMessage
	//	*ProtocolMessage_FetchMessage
	//	*ProtocolMessage_DisconnectMessage
	//	*ProtocolMessage_ConnectMessage
	//	*ProtocolMessage_NotifyMessage
	Body          isProtocolMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolMessage) Reset() {
	*x = ProtocolMessage{}
	mi := &file_mmtp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolMessage) ProtoMessage() {}

func (x *ProtocolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mmtp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolMessage.ProtoReflect.Descriptor instead.
func (*ProtocolMessage) Descriptor() ([]byte, []int) {
	return file_mmtp_proto_rawDescGZIP(), []int{4}
}

func (x *ProtocolMessage) GetProtocolMsgType() ProtocolMessageType {
	if x != nil {
		return x.ProtocolMsgType
	}
	return ProtocolMessageType_UNSPECIFIED
}

func (x *ProtocolMessage) GetBody() isProtocolMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ProtocolMessage) GetSubscribeMessage() *Subscribe {
	if x != nil {
		if x, ok := x.Body.(*ProtocolMessage_SubscribeMessage); ok {
			return x.SubscribeMessage
		}
	}
	return nil
}

func (x *ProtocolMessage) GetUnsubscribeMessage() *Unsubscribe {
	if x != nil {
		if x, ok := x.Body.(*ProtocolMessage_UnsubscribeMessage); ok {
			return x.UnsubscribeMessage
		}
	}
	return nil
}

func (x *ProtocolMessage) GetSendMessage() *Send {
	if x != nil {
		if x, ok := x.Body.(*ProtocolMessage_SendMessage); ok {
			return x.SendMessage
		}
	}
	return nil
}

func (x *ProtocolMessage) GetReceiveMessage() *Receive {
	if x != nil {
		if x, ok := x.Body.(*ProtocolMessage_ReceiveMessage); ok {
			return x.ReceiveMessage
		}
	}
	return nil
}

func (x *ProtocolMessage) GetFetchMessage() *Fetch {
	if x != nil {
		if x, ok := x.Body.(*ProtocolMessage_FetchMessage); ok {
			return x.FetchMessage
		}
	}
	return nil
}

func (x *ProtocolMessage) GetDisconnectMessage() *Disconnect {
	if x != nil {
		if x, ok := x.Body.(*ProtocolMessage_DisconnectMessage); ok {
			return x.DisconnectMessage
		}
	}
	return nil
}

func (x *ProtocolMessage) GetConnectMessage() *Connect {
	if x != nil {
		if x, ok := x.Body.(*ProtocolMessage_ConnectMessage); ok {
			return x.ConnectMessage
		}
	}
	return nil
}

func (x *ProtocolMessage) GetNotifyMessage() *Notify {
	if x != nil {
		if x, ok := x.Body.(*ProtocolMessage_NotifyMessage); ok {
			return x.NotifyMessage
		}
	}
	return nil
}

type isProtocolMessage_Body interface {
	isProtocolMessage_Body()
}

type ProtocolMessage_SubscribeMessage struct {
	SubscribeMessage *Subscribe `protobuf:"bytes,2,opt,name=subscribeMessage,proto3,oneof"`
}

type ProtocolMessage_UnsubscribeMessage struct {
	UnsubscribeMessage *Unsubscribe `protobuf:"bytes,3,opt,name=unsubscribeMessage,proto3,oneof"`
}

type ProtocolMessage_SendMessage struct {
	SendMessage *Send `protobuf:"bytes,4,opt,name=sendMessage,proto3,oneof"`
}

type ProtocolMessage_ReceiveMessage struct {
	ReceiveMessage *Receive `protobuf:"bytes,5,opt,name=receiveMessage,proto3,oneof"`
}

type ProtocolMessage_FetchMessage struct {
	FetchMessage *Fetch `protobuf:"bytes,6,opt,name=fetchMessage,proto3,oneof"`
}

type ProtocolMessage_DisconnectMessage struct {
	DisconnectMessage *Disconnect `protobuf:"bytes,7,opt,name=disconnectMessage,proto3,oneof"`
}

type ProtocolMessage_ConnectMessage struct {
	ConnectMessage *Connect `protobuf:"bytes,8,opt,name=connectMessage,proto3,oneof"`
}

type ProtocolMessage_NotifyMessage struct {
	NotifyMessage *Notify `protobuf:"bytes,9,opt,name=notifyMessage,proto3,oneof"`
}

func (*ProtocolMessage_SubscribeMessage) isProtocolMessage_Body() {}

func (*ProtocolMessage_UnsubscribeMessage) isProtocolMessage_Body() {}

func (*ProtocolMessage_SendMessage) isProtocolMessage_Body() {}

func (*ProtocolMessage_ReceiveMessage) isProtocolMessage_Body() {}

func (*ProtocolMessage_FetchMessage) isProtocolMessage_Body() {}

func (*ProtocolMessage_DisconnectMessage) isProtocolMessage_Body() {}

func (*ProtocolMessage_ConnectMessage) isProtocolMessage_Body() {}

func (*ProtocolMessage_NotifyMessage) isProtocolMessage_Body() {}

type Subscribe struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to SubjectOrDirectMessages:
	//
	//	*Subscribe_Subject
	//	*Subscribe_DirectMessages
	SubjectOrDirectMessages isSubscribe_SubjectOrDirectMessages `protobuf_oneof:"subjectOrDirectMessages"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_mmtp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_mmtp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_mmtp_proto_rawDescGZIP(), []int{5}
}

func (x *Subscribe) GetSubjectOrDirectMessages() isSubscribe_SubjectOrDirectMessages {
	if x != nil {
		return x.SubjectOrDirectMessages
	}
	return nil
}

func (x *Subscribe) GetSubject() string {
	if x != nil {
		if x, ok := x.SubjectOrDirectMessages.(*Subscribe_Subject); ok {
			return x.Subject
		}
	}
	return ""
}

func (x *Subscribe) GetDirectMessages() bool {
	if x != nil {
		if x, ok := x.SubjectOrDirectMessages.(*Subscribe_DirectMessages); ok {
			return x.DirectMessages
		}
	}
	return false
}

type isSubscribe_SubjectOrDirectMessages interface {
	isSubscribe_SubjectOrDirectMessages()
}

type Subscribe_Subject struct {
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3,oneof"`
}

type Subscribe_DirectMessages struct {
	DirectMessages bool `protobuf:"varint,2,opt,name=directMessages,proto3,oneof"`
}

func (*Subscribe_Subject) isSubscribe_SubjectOrDirectMessages() {}

func (*Subscribe_DirectMessages) isSubscribe_SubjectOrDirectMessages() {}

type Unsubscribe struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to SubjectOrDirectMessages:
	//
	//	*Unsubscribe_Subject
	//	*Unsubscribe_DirectMessages
	SubjectOrDirectMessages isUnsubscribe_SubjectOrDirectMessages `protobuf_oneof:"subjectOrDirectMessages"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Unsubscribe) Reset() {
	*x = Unsubscribe{}
	mi := &file_mmtp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unsubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unsubscribe) ProtoMessage() {}

func (x *Unsubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_mmtp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unsubscribe.ProtoReflect.Descriptor instead.
func (*Unsubscribe) Descriptor() ([]byte, []int) {
	return file_mmtp_proto_rawDescGZIP(), []int{6}
}

func (x *Unsubscribe) GetSubjectOrDirectMessages() isUnsubscribe_SubjectOrDirectMessages {
	if x != nil {
		return x.SubjectOrDirectMessages
	}
	return nil
}

func (x *Unsubscribe) GetSubject() string {
	if x != nil {
		if x, ok := x.SubjectOrDirectMessages.(*Unsubscribe_Subject); ok {
			return x.Subject
		}
	}
	return ""
}

func (x *Unsubscribe) GetDirectMessages() bool {
	if x != nil {
		if x, ok := x.SubjectOrDirectMessages.(*Unsubscribe_DirectMessages); ok {
			return x.DirectMessages
		}
	}
	return false
}

type isUnsubscribe_SubjectOrDirectMessages interface {
	isUnsubscribe_SubjectOrDirectMessages()
}

type Unsubscribe_Subject struct {
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3,oneof"`
}

type Unsubscribe_DirectMessages struct {
	DirectMessages bool `protobuf:"varint,2,opt,name=directMessages,proto3,oneof"`
}

func (*Unsubscribe_Subject) isUnsubscribe_SubjectOrDirectMessages() {}

func (*Unsubscribe_DirectMessages) isUnsubscribe_SubjectOrDirectMessages() {}

type Send struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ApplicationMessage *ApplicationMessage    `protobuf:"bytes,1,opt,name=applicationMessage,proto3" json:"applicationMessage,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Send) Reset() {
	*x = Send{}
	mi := &file_mmtp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Send) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Send) ProtoMessage() {}

func (x *Send) ProtoReflect() protoreflect.Message {
	mi := &file_mmtp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Send.ProtoReflect.Descriptor instead.
func (*Send) Descriptor() ([]byte, []int) {
	return file_mmtp_proto_rawDescGZIP(), []int{7}
}

func (x *Send) GetApplicationMessage() *ApplicationMessage {
	if x != nil {
		return x.ApplicationMessage
	}
	return nil
}

type Receive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receive) Reset() {
	*x = Receive{}
	mi := &file_mmtp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receive) ProtoMessage() {}

func (x *Receive) ProtoReflect() protoreflect.Message {
	mi := &file_mmtp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receive.ProtoReflect.Descriptor instead.
func (*Receive) Descriptor() ([]byte, []int) {
	return file_mmtp_proto_rawDescGZIP(), []int{8}
}

func (x *Receive) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageUuids  []string               `protobuf:"bytes,1,rep,name=messageUuids,proto3" json:"messageUuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_mmtp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_mmtp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_mmtp_proto_rawDescGZIP(), []int{9}
}

func (x *Filter) GetMessageUuids() []string {
	if x != nil {
		return x.MessageUuids
	}
	return nil
}

type Fetch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fetch) Reset() {
	*x = Fetch{}
	mi := &file_mmtp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fetch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fetch) ProtoMessage() {}

func (x *Fetch) ProtoReflect() protoreflect.Message {
	mi := &file_mmtp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fetch.ProtoReflect.Descriptor instead.
func (*Fetch) Descriptor() ([]byte, []int) {
	return file_mmtp_proto_rawDescGZIP(), []int{10}
}

type Disconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disconnect) Reset() {
	*x = Disconnect{}
	mi := &file_mmtp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disconnect) ProtoMessage() {}

func (x *Disconnect) ProtoReflect() protoreflect.Message {
	mi := &file_mmtp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disconnect.ProtoReflect.Descriptor instead.
func (*Disconnect) Descriptor() ([]byte, []int) {
	return file_mmtp_proto_rawDescGZIP(), []int{11}
}

type Connect struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OwnMrn         *string                `protobuf:"bytes,1,opt,name=ownMrn,proto3,oneof" json:"ownMrn,omitempty"`
	ReconnectToken *string                `protobuf:"bytes,2,opt,name=reconnectToken,proto3,oneof" json:"reconnectToken,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Connect) Reset() {
	*x = Connect{}
	mi := &file_mmtp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connect) ProtoMessage() {}

func (x *Connect) ProtoReflect() protoreflect.Message {
	mi := &file_mmtp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connect.ProtoReflect.Descriptor instead.
func (*Connect) Descriptor() ([]byte, []int) {
	return file_mmtp_proto_rawDescGZIP(), []int{12}
}

func (x *Connect) GetOwnMrn() string {
	if x != nil && x.OwnMrn != nil {
		return *x.OwnMrn
	}
	return ""
}

func (x *Connect) GetReconnectToken() string {
	if x != nil && x.ReconnectToken != nil {
		return *x.ReconnectToken
	}
	return ""
}

type Notify struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageMetadata []*MessageMetadata     `protobuf:"bytes,1,rep,name=messageMetadata,proto3" json:"messageMetadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Notify) Reset() {
	*x = Notify{}
	mi := &file_mmtp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notify) ProtoMessage() {}

func (x *Notify) ProtoReflect() protoreflect.Message {
	mi := &file_mmtp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notify.ProtoReflect.Descriptor instead.
func (*Notify) Descriptor() ([]byte, []int) {
	return file_mmtp_proto_rawDescGZIP(), []int{13}
}

func (x *Notify) GetMessageMetadata() []*MessageMetadata {
	if x != nil {
		return x.MessageMetadata
	}
	return nil
}

type ResponseMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResponseToUuid  string                 `protobuf:"bytes,1,opt,name=responseToUuid,proto3" json:"responseToUuid,omitempty"`
	Response        ResponseEnum           `protobuf:"varint,2,opt,name=response,proto3,enum=ResponseEnum" json:"response,omitempty"`
	ReasonText      *string                `protobuf:"bytes,3,opt,name=reasonText,proto3,oneof" json:"reasonText,omitempty"`
	MessageMetadata []*MessageMetadata     `protobuf:"bytes,4,rep,name=messageMetadata,proto3" json:"messageMetadata,omitempty"`
	MessageContent  []*MessageContent      `protobuf:"bytes,5,rep,name=messageContent,proto3" json:"messageContent,omitempty"`
	ReconnectToken  *string                `protobuf:"bytes,6,opt,name=reconnectToken,proto3,oneof" json:"reconnectToken,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResponseMessage) Reset() {
	*x = ResponseMessage{}
	mi := &file_mmtp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMessage) ProtoMessage() {}

func (x *ResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mmtp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMessage.ProtoReflect.Descriptor instead.
func (*ResponseMessage) Descriptor() ([]byte, []int) {
	return file_mmtp_proto_rawDescGZIP(), []int{14}
}

func (x *ResponseMessage) GetResponseToUuid() string {
	if x != nil {
		return x.ResponseToUuid
	}
	return ""
}

func (x *ResponseMessage) GetResponse() ResponseEnum {
	if x != nil {
		return x.Response
	}
	return ResponseEnum_UNSPECIFIED_RESPONSE
}

func (x *ResponseMessage) GetReasonText() string {
	if x != nil && x.ReasonText != nil {
		return *x.ReasonText
	}
	return ""
}

func (x *ResponseMessage) GetMessageMetadata() []*MessageMetadata {
	if x != nil {
		return x.MessageMetadata
	}
	return nil
}

func (x *ResponseMessage) GetMessageContent() []*MessageContent {
	if x != nil {
		return x.MessageContent
	}
	return nil
}

func (x *ResponseMessage) GetReconnectToken() string {
	if x != nil && x.ReconnectToken != nil {
		return *x.ReconnectToken
	}
	return ""
}

type MessageMetadata struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Uuid          string                    `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Header        *ApplicationMessageHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageMetadata) Reset() {
	*x = MessageMetadata{}
	mi := &file_mmtp_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageMetadata) ProtoMessage() {}

func (x *MessageMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_mmtp_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageMetadata.ProtoReflect.Descriptor instead.
func (*MessageMetadata) Descriptor() ([]byte, []int) {
	return file_mmtp_proto_rawDescGZIP(), []int{15}
}

func (x *MessageMetadata) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MessageMetadata) GetHeader() *ApplicationMessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type MessageContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Msg           *ApplicationMessage    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageContent) Reset() {
	*x = MessageContent{}
	mi := &file_mmtp_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContent) ProtoMessage() {}

func (x *MessageContent) ProtoReflect() protoreflect.Message {
	mi := &file_mmtp_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContent.ProtoReflect.Descriptor instead.
func (*MessageContent) Descriptor() ([]byte, []int) {
	return file_mmtp_proto_rawDescGZIP(), []int{16}
}

func (x *MessageContent) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MessageContent) GetMsg() *ApplicationMessage {
	if x != nil {
		return x.Msg
	}
	return nil
}

var File_mmtp_proto protoreflect.FileDescriptor

var file_mmtp_proto_rawDesc = string([]byte{
	0x0a, 0x0a, 0x6d, 0x6d, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x79, 0x0a, 0x12,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x8d, 0x02, 0x0a, 0x18, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x2d, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74,
	0x73, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x23, 0x0a, 0x0a, 0x71, 0x6f, 0x73, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0a, 0x71, 0x6f, 0x73, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x12, 0x2a, 0x0a, 0x10, 0x62, 0x6f, 0x64, 0x79, 0x53, 0x69,
	0x7a, 0x65, 0x4e, 0x75, 0x6d, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x10, 0x62, 0x6f, 0x64, 0x79, 0x53, 0x69, 0x7a, 0x65, 0x4e, 0x75, 0x6d, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x42, 0x14, 0x0a, 0x12, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4f, 0x72, 0x52,
	0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x71, 0x6f, 0x73,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x2c, 0x0a, 0x0a, 0x52, 0x65, 0x63, 0x69, 0x70,
	0x69, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x69, 0x70,
	0x69, 0x65, 0x6e, 0x74, 0x73, 0x22, 0xc9, 0x01, 0x0a, 0x0b, 0x4d, 0x6d, 0x74, 0x70, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x3c, 0x0a,
	0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3c, 0x0a, 0x0f, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x22, 0x82, 0x04, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3e, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x73,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x38, 0x0a, 0x10, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x48, 0x00, 0x52, 0x10, 0x73,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x3e, 0x0a, 0x12, 0x75, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x55, 0x6e,
	0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x48, 0x00, 0x52, 0x12, 0x75, 0x6e, 0x73,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x29, 0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x73,
	0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x32, 0x0a, 0x0e, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x48, 0x00, 0x52, 0x0e,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2c,
	0x0a, 0x0c, 0x66, 0x65, 0x74, 0x63, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x48, 0x00, 0x52, 0x0c,
	0x66, 0x65, 0x74, 0x63, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3b, 0x0a, 0x11,
	0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x11, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x32, 0x0a, 0x0e, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x0e, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2f, 0x0a,
	0x0d, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x48, 0x00, 0x52,
	0x0d, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x06,
	0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x6c, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x12, 0x1a, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12,
	0x28, 0x0a, 0x0e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0e, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x42, 0x19, 0x0a, 0x17, 0x73, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x4f, 0x72, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x22, 0x6e, 0x0a, 0x0b, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x12, 0x1a, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12,
	0x28, 0x0a, 0x0e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0e, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x42, 0x19, 0x0a, 0x17, 0x73, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x4f, 0x72, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x22, 0x4b, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x43, 0x0a, 0x12,
	0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x12, 0x61,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x3a, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x12, 0x24, 0x0a, 0x06,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x88,
	0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x2c, 0x0a,
	0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x55, 0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x55, 0x75, 0x69, 0x64, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x22, 0x0c, 0x0a, 0x0a, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x22, 0x71, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1b, 0x0a,
	0x06, 0x6f, 0x77, 0x6e, 0x4d, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x06, 0x6f, 0x77, 0x6e, 0x4d, 0x72, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x2b, 0x0a, 0x0e, 0x72, 0x65,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x01, 0x52, 0x0e, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6f, 0x77, 0x6e, 0x4d,
	0x72, 0x6e, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x44, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12,
	0x3a, 0x0a, 0x0f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x0f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0xcd, 0x02, 0x0a, 0x0f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x26, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x6f, 0x55, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x54, 0x6f, 0x55, 0x75, 0x69, 0x64, 0x12, 0x29, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x23, 0x0a, 0x0a, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x54, 0x65, 0x78, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x54, 0x65, 0x78, 0x74, 0x88, 0x01, 0x01, 0x12, 0x3a, 0x0a, 0x0f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x0f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x37, 0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x0e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x2b, 0x0a, 0x0e,
	0x72, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0e, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x72, 0x65, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x58, 0x0a, 0x0f, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x12, 0x31, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x4b, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x2a, 0x4e, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a,
	0x13, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x5f, 0x4d, 0x45, 0x53,
	0x53, 0x41, 0x47, 0x45, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43,
	0x4f, 0x4c, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10,
	0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45,
	0x10, 0x02, 0x2a, 0xd1, 0x01, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x53,
	0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45,
	0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x55, 0x4e, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42,
	0x45, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x53,
	0x45, 0x4e, 0x44, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x03, 0x12, 0x13, 0x0a,
	0x0f, 0x52, 0x45, 0x43, 0x45, 0x49, 0x56, 0x45, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45,
	0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x46, 0x45, 0x54, 0x43, 0x48, 0x5f, 0x4d, 0x45, 0x53, 0x53,
	0x41, 0x47, 0x45, 0x10, 0x05, 0x12, 0x16, 0x0a, 0x12, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e, 0x4e,
	0x45, 0x43, 0x54, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x06, 0x12, 0x13, 0x0a,
	0x0f, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45,
	0x10, 0x07, 0x12, 0x12, 0x0a, 0x0e, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x59, 0x5f, 0x4d, 0x45, 0x53,
	0x53, 0x41, 0x47, 0x45, 0x10, 0x08, 0x2a, 0x3d, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x14, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x47, 0x4f, 0x4f, 0x44, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x02, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x6d, 0x6d, 0x74, 0x70, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_mmtp_proto_rawDescOnce sync.Once
	file_mmtp_proto_rawDescData []byte
)

func file_mmtp_proto_rawDescGZIP() []byte {
	file_mmtp_proto_rawDescOnce.Do(func() {
		file_mmtp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mmtp_proto_rawDesc), len(file_mmtp_proto_rawDesc)))
	})
	return file_mmtp_proto_rawDescData
}

var file_mmtp_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_mmtp_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_mmtp_proto_goTypes = []any{
	(MsgType)(0),                     // 0: MsgType
	(ProtocolMessageType)(0),         // 1: ProtocolMessageType
	(ResponseEnum)(0),                // 2: ResponseEnum
	(*ApplicationMessage)(nil),       // 3: ApplicationMessage
	(*ApplicationMessageHeader)(nil), // 4: ApplicationMessageHeader
	(*Recipients)(nil),               // 5: Recipients
	(*MmtpMessage)(nil),              // 6: MmtpMessage
	(*ProtocolMessage)(nil),          // 7: ProtocolMessage
	(*Subscribe)(nil),                // 8: Subscribe
	(*Unsubscribe)(nil),              // 9: Unsubscribe
	(*Send)(nil),                     // 10: Send
	(*Receive)(nil),                  // 11: Receive
	(*Filter)(nil),                   // 12: Filter
	(*Fetch)(nil),                    // 13: Fetch
	(*Disconnect)(nil),               // 14: Disconnect
	(*Connect)(nil),                  // 15: Connect
	(*Notify)(nil),                   // 16: Notify
	(*ResponseMessage)(nil),          // 17: ResponseMessage
	(*MessageMetadata)(nil),          // 18: MessageMetadata
	(*MessageContent)(nil),           // 19: MessageContent
}
var file_mmtp_proto_depIdxs = []int32{
	4,  // 0: ApplicationMessage.header:type_name -> ApplicationMessageHeader
	5,  // 1: ApplicationMessageHeader.recipients:type_name -> Recipients
	0,  // 2: MmtpMessage.msgType:type_name -> MsgType
	7,  // 3: MmtpMessage.protocolMessage:type_name -> ProtocolMessage
	17, // 4: MmtpMessage.responseMessage:type_name -> ResponseMessage
	1,  // 5: ProtocolMessage.protocolMsgType:type_name -> ProtocolMessageType
	8,  // 6: ProtocolMessage.subscribeMessage:type_name -> Subscribe
	9,  // 7: ProtocolMessage.unsubscribeMessage:type_name -> Unsubscribe
	10, // 8: ProtocolMessage.sendMessage:type_name -> Send
	11, // 9: ProtocolMessage.receiveMessage:type_name -> Receive
	13, // 10: ProtocolMessage.fetchMessage:type_name -> Fetch
	14, // 11: ProtocolMessage.disconnectMessage:type_name -> Disconnect
	15, // 12: ProtocolMessage.connectMessage:type_name -> Connect
	16, // 13: ProtocolMessage.notifyMessage:type_name -> Notify
	3,  // 14: Send.applicationMessage:type_name -> ApplicationMessage
	12, // 15: Receive.filter:type_name -> Filter
	18, // 16: Notify.messageMetadata:type_name -> MessageMetadata
	2,  // 17: ResponseMessage.response:type_name -> ResponseEnum
	18, // 18: ResponseMessage.messageMetadata:type_name -> MessageMetadata
	19, // 19: ResponseMessage.messageContent:type_name -> MessageContent
	4,  // 20: MessageMetadata.header:type_name -> ApplicationMessageHeader
	3,  // 21: MessageContent.msg:type_name -> ApplicationMessage
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_mmtp_proto_init() }
func file_mmtp_proto_init() {
	if File_mmtp_proto != nil {
		return
	}
	file_mmtp_proto_msgTypes[1].OneofWrappers = []any{
		(*ApplicationMessageHeader_Subject)(nil),
		(*ApplicationMessageHeader_Recipients)(nil),
	}
	file_mmtp_proto_msgTypes[3].OneofWrappers = []any{
		(*MmtpMessage_ProtocolMessage)(nil),
		(*MmtpMessage_ResponseMessage)(nil),
	}
	file_mmtp_proto_msgTypes[4].OneofWrappers = []any{
		(*ProtocolMessage_SubscribeMessage)(nil),
		(*ProtocolMessage_UnsubscribeMessage)(nil),
		(*ProtocolMessage_SendMessage)(nil),
		(*ProtocolMessage_ReceiveMessage)(nil),
		(*ProtocolMessage_FetchMessage)(nil),
		(*ProtocolMessage_DisconnectMessage)(nil),
		(*ProtocolMessage_ConnectMessage)(nil),
		(*ProtocolMessage_NotifyMessage)(nil),
	}
	file_mmtp_proto_msgTypes[5].OneofWrappers = []any{
		(*Subscribe_Subject)(nil),
		(*Subscribe_DirectMessages)(nil),
	}
	file_mmtp_proto_msgTypes[6].OneofWrappers = []any{
		(*Unsubscribe_Subject)(nil),
		(*Unsubscribe_DirectMessages)(nil),
	}
	file_mmtp_proto_msgTypes[8].OneofWrappers = []any{}
	file_mmtp_proto_msgTypes[12].OneofWrappers = []any{}
	file_mmtp_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mmtp_proto_rawDesc), len(file_mmtp_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mmtp_proto_goTypes,
		DependencyIndexes: file_mmtp_proto_depIdxs,
		EnumInfos:         file_mmtp_proto_enumTypes,
		MessageInfos:      file_mmtp_proto_msgTypes,
	}.Build()
	File_mmtp_proto = out.File
	file_mmtp_proto_goTypes = nil
	file_mmtp_proto_depIdxs = nil
}
